### ISSUE TITLE
Name the macro just Debug

### ISSUE THREAD

**Issue by mzabaluev** [panicbit/custom_debug#12]
Similarly to `thiserror::Error` it would be stylistically nice to invoke the macro with just `#[derive(Debug)]`, or `#[derive(custom_debug::Debug)]` for clarity. The macro name should signify the actual trait that is implemented.

**Comment by panicbit** [comment]
That's a great idea!

**Comment by panicbit** [comment]
This is published as 0.5.0 now :)

**Comment by mzabaluev** [comment]
Thank you, that was quick :)
