### ISSUE TITLE
Support `skip_if` attribute

### ISSUE THREAD

**Issue by adwhit** [panicbit/custom_debug#17]
This is just a suggestion. Add a `skip_if` attribute, modelled on `serde`s [`skip_serializing_if`](https://serde.rs/field-attrs.html#skip_serializing_if) attribute.

Sometimes I have lots of optional fields that are very noisey in the debug output. It would be nice to be able to skip a field if it is None.

e.g.

```rust
#[derive(custom_debug::Debug)]
struct BigStruct {
    f1: Option<int>,
    #[debug(skip_if = "Option::is_none")]
    f2: Option<f64>,
    // ...
}
```
Inside the desugar, we would see something like:

```rust
let f = f.debug_struct("BigStruct").field("f1", /*...*/);
let f = if !Option::is_none(&f.f2) {
    f.field("f2", /*...*/)
} else {
    f
};
// etc
```

**Comment by panicbit** [comment]
![good-news-everyone-435933755](https://github.com/panicbit/custom_debug/assets/628445/3ec77312-86f2-48c8-8519-914b81df46f6)

This is finally implemented and available in version `0.6.1`! 🥳
