### ISSUE TITLE
Upgrade syn & synstructure

### ISSUE THREAD

**Issue by RReverser** [panicbit/custom_debug#18]
This is the only crate in couple of my projects that is still on `syn 1.0`, causing much slower builds due to Cargo having to build both `syn 1.0` and `syn 2.0` versions in parallel.

Same for `synstructure` where newer version has already migrated to `syn 2.0`.

While not a big deal, it would be nice to upgrade those deps for faster compilation times.

**Comment by panicbit** [comment]
I'm going to try to upgrade those deps now, wish me luck 🤡

**Comment by panicbit** [comment]
Published version [`0.6.0` on crates.io](https://crates.io/crates/custom_debug/0.6.0)

**Comment by RReverser** [comment]
Awesome, thanks!
