### ISSUE TITLE
Provide ready-made functions for `with=`.

### ISSUE THREAD

**Issue by vi** [panicbit/custom_debug#9]
Maybe `custom_debug_derive` apart from the main derive macro should also provide some pre-made functions for using with `#[debug(with = "custom_debug_derive::somefunc")]`?

For example, this may include the `hex` function used as example:

```rust
pub fn hex<T: fmt::Debug>(n: &T, f: &mut fmt::Formatter) -> fmt::Result {
    write!(f, "0x{:02X?}", n)
}
```

Also some function for printing byte buffers in hex:

```rust

pub fn hexbuf(v: &impl AsRef<[u8]>, f: &mut std::fmt::Formatter) -> std::fmt::Result {
    write!(f, "b\"")?;
    for x in v.as_ref() {
        write!(f, "\\x{:02x}", x)?;
    }
    write!(f, "\"")?;
    Ok(())
}

pub fn hexbuf_str(v: &impl AsRef<[u8]>, f: &mut std::fmt::Formatter) -> std::fmt::Result {
    write!(f, "b\"")?;
    for x in v.as_ref() {
        match x {
            | b'0'..=b'9' 
            | b'a'..=b'z' 
            | b'A'..=b'Z'
            | b'~' | b'!' | b'@' | b'#' | b'$'
            | b'%' | b'^' | b'&' | b'*' | b'('
            | b')' | b'-' | b'_' | b'=' | b'+'
            | b'`' | b'[' | b']' | b'{' | b'}'
            | b'|' | b';' | b':' | b'\''
            | b',' | b'<' | b'.' | b'>' | b'/' | b'?'
            => write!(f, "{}", *x as char)?,
            b'\\' => write!(f, "\\\\")?,
            b'"' => write!(f, "\\\"")?,
            _ => write!(f, "\\x{:02x}", x)?,
        }
    }
    write!(f, "\"")?;
    Ok(())
}
```

**Comment by panicbit** [comment]
Great idea!

**Comment by panicbit** [comment]
I'll see if I can get something done during the weekend :)

**Comment by panicbit** [comment]
I've split the project into two crates now, `custom_debug` and `custom_debug_derive`, to allow providing utilities along the macro.

**Comment by panicbit** [comment]
Implemented in 376a52e. I've published this this as `0.4.0` on crates.io.
Don't forget to switch to the `custom_debug` crate in your deps! :tada:

**Comment by panicbit** [comment]
If you have more ideas I'd be happy to implement them :)

**Comment by vi** [comment]
Ideas:

Byte buffer related:

* Printing only length and/or only the beginning of the buffer
* Short format (`2020EF` instead of `b"\x20\x20\xef"`)

General:

* A function that output only the name of struct, without content. Something like

        #[debug(with="norecurse")]
        cache: Option<BigFatVerboseStruct>

    User wants to know if it's `None` or `Some`, but without descending into. Just show which enum discriminant is used.

* RLE-encoded vector output: `[1,3,7,7,0,0,0,0,0,0,0,0,0,0,0,0]` -> `[1, 3, 7 x 2, 0 x 12]`.
* Hashed output. Print short hash instead of actual big content.
* Smart `{:#?}` output which auto-collapses short enough things to single lines.
* [loglevel-dependent](https://docs.rs/log/0.4.10/log/macro.log_enabled.html) inclusion of fields in debug output.

**Comment by panicbit** [comment]
Thanks a lot!

**Comment by vi** [comment]
Why no `hex` function in `custom_debug`, only `hexstr`s?

**Comment by panicbit** [comment]
Yeah, I should add that too.
